name: state_comparison
description: A state management solutions comparison
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  app_ui: 
    path: packages/app_ui
  flutter:
    sdk: flutter
  products_repository:
    path: packages/products_repository
  products_service:
    path: packages/products_service
  provider: ^6.0.3  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

