name: state_comparison
description: A state management solutions comparison
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  app_ui: 
    path: packages/app_ui
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  products_repository:
    path: packages/products_repository
  products_service:
    path: packages/products_service
  # provider
  provider: ^6.0.3  
  # riverpod
  hooks_riverpod: ^2.0.0-dev.9
  # redux
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  # get_it
  get_it: ^7.2.0
  get_it_mixin: ^3.1.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

